version: '3.8'

services:
  ecommerce-api:
    image: ecommerce-api-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=ecommerce-db;Port=5432;Database=ECommerceDb;Username=postgres;Password=mysecretpassword;
    depends_on:
      - ecommerce-db

  ecommerce-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=ECommerceDb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: