services:
  ecommerce-api:
    image: ecommerce-api-image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreConnection=Host=ecommerce-db;Port=5432;Database=ECommerceDb;Username=postgres;Password=mysecretpassword;
      - ConnectionStrings__Redis=ecommerce-redis:6379
    depends_on:
      - ecommerce-db
      - ecommerce-redis

  ecommerce-db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=ECommerceDb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  ecommerce-redis:
    image: redis:alpine
    container_name: ecommerce_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: